# Generated by Django 5.2.1 on 2025-10-04 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('venue', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.CharField()),
                ('languages', models.JSONField(default=list)),
                ('age', models.CharField()),
                ('organization', models.CharField(max_length=100)),
                ('landscape', models.ImageField(upload_to='banners/')),
                ('portrait', models.ImageField(upload_to='banners/')),
                ('is_popular', models.BooleanField(default=False)),
                ('status', models.CharField(default='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='category.category')),
                ('organizer', models.ForeignKey(limit_choices_to={'role': 'organizer'}, on_delete=django.db.models.deletion.CASCADE, related_name='event_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('title', 'organizer')},
            },
        ),
    ]
