# Generated by Django 5.2.1 on 2025-09-16 14:06

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('venue', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.CharField()),
                ('language', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None)),
                ('age', models.CharField()),
                ('organization', models.CharField(max_length=100)),
                ('wallpaper', models.ImageField(upload_to='banners/')),
                ('portrait', models.ImageField(upload_to='banners/')),
                ('status', models.CharField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(limit_choices_to={'role': 'organizer'}, on_delete=django.db.models.deletion.CASCADE, related_name='event_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('title', 'organizer')},
            },
        ),
    ]
