from django.db import models
from eventapp.models import Event
from accountapp.models import User
# Create your models here.
class Tier(models.Model):
    #id autogenerated
    name = models.CharField()
    event = models.ForeignKey(Event , on_delete=models.CASCADE , related_name="tier") # will hold the primary key of Event table
    organizer = models.ForeignKey(User , on_delete=models.CASCADE ,limit_choices_to={'role': 'organizer'},  related_name="tier")
    price = models.IntegerField()
    benefits = models.JSONField(default=list) # ["front row" , "Ac" , "food"]
    available_seats = models.IntegerField()
    discount =  models.DecimalField(max_digits=5 , decimal_places=2 , null=True , blank=True)
    tax =  models.DecimalField(max_digits=5 , decimal_places=2 , null=True , blank=True)
    
    
    def __str__(self):
        return f"{self.name}"


