from django.db import models
from eventapp.models import Event
from accountapp.models import User
# Create your models here.
class Tier(models.Model):
    # name = models.CharField()
    # price = models.DecimalField(max_digits=8 , decimal_places=2)
    # quantityAvailable = models.IntegerField()
    # benefits = models.JSONField() # ["Front row", "Free swag"]
    #id autogenerated
    ticket_types = models.JSONField(default=dict)
    seats = models.JSONField(default=dict)
    event = models.ForeignKey(Event , on_delete=models.CASCADE , related_name="tier") # will hold the primary key of Event table
    organizer = models.ForeignKey(User , on_delete=models.CASCADE ,limit_choices_to={'role': 'organizer'},  related_name="tier")



    def __str__(self):
        return f"{self.event.title}-{self.organizer}"


# {
#   _id: ObjectId,
#   eventId: ObjectId,
#   name: "VIP",
#   price: 2000,
#   quantityAvailable: 100,
#   benefits: ["Front row", "Free swag"]
# }

# {
    
#     ticket_types:{"VIP":1000  , "Early bird":500},
#     seats : {"VIP":"100" , "Early bird":300},
#     event: Startup Summit 2025,
    
# }