# Generated by Django 5.2.1 on 2025-09-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('organizer', 'Organizer'), ('user', 'User')], max_length=10),
        ),
    ]
